name: Build & Deploy Payavel Docs

on:
  push:
    branches:
      - master
    paths:
      - 'payavel/**/*'
  pull_request:
    branches:
      - master
    paths:
      - 'payavel/**/*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build & Deploy
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install VitePress
        run: npm install --dev

      - name: Build Orchestration Docs
        run: npm run payavel:build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy payavel/.vitepress/dist --project-name=payavel
